[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+avx2"]
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+avx2"]
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crc"]
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]
[target.wasm32-wasi-preview1-threads]
rustflags = ["-C", "target-feature=+simd128"]
